return
{ { properties = { floating = true,
      screen = "primary",
      tag = 3 },
    rule = { class = "Skype" } },
  { properties = { screen = "primary",
      tag = 3 },
    rule = { class = "Viber" } },
  { properties = { screen = "primary",
      tag = 2 },
    rule = { class = "Firefox" } },
  { properties = { screen = "primary",
      tag = 2 },
    rule = { class = "Chromium" } },
  { properties = { screen = "primary",
      tag = 2 },
    rule = { class = "Thunderbird" } },
  { properties = { screen = "primary",
      tag = 3 },
    rule = { class = "Emacs" } },
  { properties = { screen = "primary",
      tag = 5 },
    rule = { class = "Steam" } },
  { properties = { screen = "primary",
      tag = 6 },
    rule = { class = "Transmission-gtk" } },
  { properties = { tag = 6 },
    rule = { class = "gimp" } },
  { properties = { floating = true },
    rule = { class = "MPlayer" } },
  { properties = { floating = true },
    rule = { class = "feh" } },
  { properties = { tag = 4 },
    rule = { class = "Easytag" } },
  { properties = { tag = 6 },
    rule = { class = "Gnucash" } },
  { properties = { tag = 4 },
    rule = { class = "Android SDK Manager" } },
  { properties = { tag = 1 },
    rule = { class = "Quasselclient" } },
  { properties = { screen = "primary",
      tag = 1 },
    rule = { class = "Hexchat" } },
  { properties = { tag = 5 },
    rule = { class = "Filezilla" } },
  { properties = { tag = 6 },
    rule = { class = "Gimp-2.8" } },
  { properties = { tag = 5 },
    rule = { class = "VirtualBox" } },
  { properties = { tag = 4 },
    rule = { class = "jetbrains-android-studi" } },
  { properties = { tag = 4 },
    rule = { class = "jetbrains-android-studio" } },
  { properties = { tag = 4 },
    rule = { class = "Monitor" } },
  { properties = { tag = 4 },
    rule = { class = "VisualVM 1.3.8" } },
  { properties = { tag = 4 },
    rule = { class = "Player" } },
  { properties = { screen = "primary",
      tag = 6 },
    rule = { class = "Gimp" } },
  { properties = {  },
    rule = { class = "Gnome-alsamixer" } },
  { properties = { screen = "primary",
      tag = 1 },
    rule = { class = "Terminator" } },
  { properties = {  },
    rule = { class = "Evince" } },
  { properties = { screen = "primary",
      tag = 6 },
    rule = { class = "MATLAB R2015" } },
  { properties = { screen = "primary",
      tag = 3 },
    rule = { class = "ViberPC" } } }